### ISSUE TITLE
Lines spacing

### ISSUE THREAD

**Issue by williamgferreira** [solmatas/BitterPro#20]
Hello,

I consider the Bitter font to be perfect and I use it in practically all my projects. recently when downloading the latest version from google fonts I noticed that there was an updated version, but this new version was actually 'Bitter Pro', and the spacing between the lines of it was quite different from the previous one.

At first I was willing to replace everything I have with the old font for the new one. However, as I used the new one I noticed, at least in my opinion, that it already seemed to be right, in larger texts it was always necessary to define a larger spacing in the app for good aesthetics.

Having said that, I would like to ask if this is a desired feature for this new version, or is it really something that will be tweaked at some point in the future.

**Comment by solmatas** [comment]
Hi William,
that feature is probably not going to change in the future. If you have a specific requirement with Bitter Pro, you can send me an email and I can help with that. 
There is a contact form on my website.
