### ISSUE TITLE
.notdef glyph contours flip direction

### ISSUE THREAD

**Issue by Lorp** [solmatas/BitterPro#21]
There’s a problem in the .notdef glyph (both Roman and Italic) such that it flips direction twice as the `wght` axis is adjusted from 100 to 900. The flipping has these properties:

* `wght`=100: outlines have correct orientation
* `wght`=500: outlines have incorrect orientation
* `wght`=900: outlines have correct orientation, but appear scaled by ~102%  compared with the glyph at `wght`=100 and `wght`=500

The intermediate gvar pivoting around 500 is curious as this font does not have a master at that location, only masters at 100 and 900.

https://github.com/solmatas/BitterPro/assets/587440/5c82fbca-906c-449e-8fea-cccb603cbad8

**Comment by solmatas** [comment]
Updated the files =)

**Comment by Lorp** [comment]
Oops, must have missed Sol’s update.
